try_catch_catch_finally() is
    try
        let x = 1;

    catch 
        
    catch   

    finally
        let y = 2;
    yrt
    
    return;
si
