namespace Test is













    use IO.Std;
    use BoundsException = System.IndexOutOfRangeException;

    use System.Exception;

    class Main is
        entry() static is
            

            test("expect finally only", null);

            test("expect my exception catch and finally", MyException("my exception"));

            test("expect other exception catch and finally", Exception("system exception"));

            test("expect other exception catch and finally", BoundsException("bounds exception"));
        si

        test(message: string, ex: Exception) static is
            Std.out.write_line("before: " + message);

            try
                Std.out.write_line("start: " + message);

                if ex? then
                    Std.out.write_line("will throw: " + ex.get_type().name);

                    throw ex;

                    Std.out.write_line("should not be reachable");
                else
                    Std.out.write_line("will not throw");                    
                fi
                
            catch exa: MyException
                Std.out.write_line("caught my exception: " + exa.message);

            catch exb: Exception
                Std.out.write_line("caught other exception: " + exb.message);

            finally
                Std.out.write_line("finally: " + message);                
            yrt

            Std.out.write_line("after: " + message);
        si        
    si

    class MyException: Exception is
        init(message: string) is
            super.init(message);
        si
    si    
si