namespace Test is
    use System.Exception;

    use Std = IO.Std;
    
    class Main is
        entry() static is
            

            try
                for i in 0..10 do
                    Std.out.write_line("outer: " + i);
    
                    if i == 3 \/ i == 7 then
                        Std.out.write_line("outer: will continue");
                        continue;
                    fi
                    
                    if i == 8 then
                        Std.out.write_line("outer: will break");
                        continue;                        
                    fi

                    Std.out.write_line("outer: did not continue or break");

                    try
                        for j in 0..10 do
                            Std.out.write_line("inner: " + j);
                                                        
                            if j >= 4 /\ j <= 5 then
                                Std.out.write_line("inner: will continue");
                                continue;
                            fi                                

                            if j >= 7 then
                                Std.out.write_line("inner: will break");
                                break;
                            fi

                            Std.out.write_line("inner: did not continue or break");
                        od

                    catch ex: Exception
                        Std.out.write_line("outer: caught: " + ex.message);
                    yrt        
                od

            catch ex: Exception
                Std.out.write_line("main: caught: " + ex.message);
            yrt
        si
    si

    class MyException: Exception is
        init(message: string) is super.init(message); si
    si   
si