try_catch_variable_finally() is
    try
        let x = 1;

    catch ex: System.Exception

    finally

    return;
si
